// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ2MNDm1EF0ivt41xwULo7DNAiN_EVq3Y',
    appId: '1:711131970078:web:b351d601b7ea11d8148c0f',
    messagingSenderId: '711131970078',
    projectId: 'project-college-5e5e3',
    authDomain: 'project-college-5e5e3.firebaseapp.com',
    databaseURL: 'https://project-college-5e5e3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project-college-5e5e3.appspot.com',
    measurementId: 'G-TC9E8R4B6R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnHVxQqd98Jrh030ACXkrg0ytMreCc6T8',
    appId: '1:711131970078:android:434ad44383fea554148c0f',
    messagingSenderId: '711131970078',
    projectId: 'project-college-5e5e3',
    databaseURL: 'https://project-college-5e5e3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project-college-5e5e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYZ4IBokzXy9ERN7aUBM9ez7Iw4hCFL_w',
    appId: '1:711131970078:ios:9d5107b78deece72148c0f',
    messagingSenderId: '711131970078',
    projectId: 'project-college-5e5e3',
    databaseURL: 'https://project-college-5e5e3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project-college-5e5e3.appspot.com',
    androidClientId: '711131970078-ft4uvqsefvm8bbk4hvp37295nrs5lifd.apps.googleusercontent.com',
    iosClientId: '711131970078-ch06l1k0fd0usda1rgnkna33d9jhf022.apps.googleusercontent.com',
    iosBundleId: 'com.example.vani',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYZ4IBokzXy9ERN7aUBM9ez7Iw4hCFL_w',
    appId: '1:711131970078:ios:15dccca9027efad1148c0f',
    messagingSenderId: '711131970078',
    projectId: 'project-college-5e5e3',
    databaseURL: 'https://project-college-5e5e3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project-college-5e5e3.appspot.com',
    androidClientId: '711131970078-ft4uvqsefvm8bbk4hvp37295nrs5lifd.apps.googleusercontent.com',
    iosClientId: '711131970078-sn7b934lpur6nlvpbuas91089e94u47m.apps.googleusercontent.com',
    iosBundleId: 'com.example.vani.RunnerTests',
  );
}
